name: comment

on:
  issue_comment:
    types: [created]

env:
  SERVICE: ras-rm-benchmark

jobs:
  comment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/deploy')
    steps:
      - name: Retrieving PR tag
        if: github.ref != 'refs/heads/main'
        id: tag
        run: |
          PR_NUMBER=pr-$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          echo "The PR tag is $PR_NUMBER"

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GCR_KEY }}
          export_default_credentials: true

      - uses: onsdigital/ras-rm-spinnaker-action@main
        with:
          comment-body: ${{ github.event.comment.body }}
          gcp-project: ${{ secrets.GOOGLE_PROJECT_ID }}
          bot-token: ${{ secrets.BOT_TOKEN }}
          spinnaker-topic: ${{ secrets.SPINNAKER_TOPIC }}
          artifact-bucket: ${{ secrets.ARTIFACT_BUCKET }}
          helm-chart: ${{ env.SERVICE }}/${{ env.SERVICE }}-$PR_NUMBER.tgz
